return {
    diagnostics = {
        Error = ' ',
        Warn = ' ',
        Hint = ' ',
        Info = ' ',
    },
    git = {
        git = ' ',
        added = ' ',
        modified = ' ',
        removed = ' ',
    },
    kinds = {
        Array = ' 󰅪 ',
        Boolean = ' ◩ ',
        Class = ' 󰠱 ',
        Color = '  ',
        Constant = ' 󰏿 ',
        Constructor = '  ',
        Copilot = '  ',
        Enum = ' 󰕘 ',
        EnumMember = ' 󰕘 ',
        Event = '  ',
        Field = '  ',
        File = '  ',
        Folder = '  ',
        Function = ' 󰊕 ',
        Interface = ' 󰕘 ',
        Key = ' 󰌋 ',
        Keyword = '  ',
        Method = '  ',
        Module = '  ',
        Namespace = '  ',
        Null = ' 󰟢 ',
        Number = ' 󰎠 ',
        Object = ' 󰅩 ',
        Operator = ' 󰆕 ',
        Package = '  ',
        Property = '  ',
        Reference = '  ',
        Snippet = '  ',
        String = ' 󰀬 ',
        Struct = ' 󰙅 ',
        Text = '  ',
        TypeParameter = ' 󰊄 ',
        Unit = '  ',
        Value = '  ',
        Variable = '󰆧 ',
    },
    spinner = {
        dot = { '⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏' },
        circle = { '  ', '  ', '  ', '  ', '  ', '  ' },
    },
    todolist = {
        todo = '  ',
        wip = ' 󰦕 ',
        done = '  ',
    },
}
