require('modules.plugins.packer')
require('modules.plugins.blankline')
require('modules.plugins.colorizer')
require('modules.plugins.cmp')
require('modules.plugins.formatter')
require('modules.plugins.gitsigns')
require('modules.plugins.telescope')
require('modules.plugins.trouble')
