name: Docker Image CI

on:
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag neovim
      - name: run the Docker image
        id: record
        run: |
          docker run -d  --name neovim  neovim tail -f /dev/null
          docker exec -i neovim /bin/sh -c "nvim --headless --startuptime log +qa || exit 0"
          echo  "$(docker exec -i neovim /bin/sh -c "cat log" | sed -n 'x;$p;d' | cut -d' ' -f1 | sed 's/\..*//' | sed 's/^0*//' )"
