name: Docker Image CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag neovim
      - name: run the Docker image
        id: record
        run: |
          docker run -d  --name neovim  neovim tail -f /dev/null
          docker exec -i neovim /bin/sh -c "nvim --headless --startuptime log +qa || exit 0"
          echo  "##[set-output name=startuptime;]$(docker exec -i neovim /bin/bash -c "cat log" | tail -n 1 |awk '{print $1}' |sed 's/\..*//' | sed 's/^0*//' )"
      - name: Bring Your Own Badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: "startuptime"
          LABEL: "startuptime"
          STATUS: ${{ steps.record.outputs.startuptime }} ms
          COLOR: blue
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
