name: Docker Image CI

on:
  pull_request:
    branches: ["dev"]
  push:

jobs:
  docker:
    name: Docker build & test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag neovim

      - name: Run container
        run: |
          docker run -d --name neovim neovim tail -f /dev/null

      - name: Run Neovim headless
        run: |
          docker exec neovim sh -c "nvim --headless --startuptime log +qa || true"

      - name: Extract startup time
        run: |
          docker exec neovim sh -c "tail -n 1 log" | awk '{print int($1)}'

      - name: Cleanup
        if: always()
        run: docker rm -f neovim
