name: Formating

on: [push, pull_request_target]

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: .
          version: 2.0.2
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore(style): stylua format"
          branch: ${{ github.head_ref }}

  rumdl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Lint Markdown
        uses: rvben/rumdl@v0
        with:
          config: .rumdl.toml
          report-type: annotations
