name: Formating

on: [push, pull_request_target]

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: .
          version: 0.15.2
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Format with stylua"
          branch: ${{ github.head_ref }}
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          command: fix
          globs: |
            *.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Format with markdownlint"
          branch: ${{ github.head_ref }}
